version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ../input-files:/opt/app/aip/files
    env_file: .env
    environment:
      DEBUG: 'true'
  
  celery:
    build: ./web
    command: bash -c "cd aip && celery -A aip_project worker -l info"
    env_file: .env
    depends_on:
      - postgres
      - redis
  
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"


