version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-files:/files
    env_file: .env
    command: /usr/local/bin/gunicorn aip_project.wsgi:application -w 2 -b :8000
  
  celery:
    build: ./web
    command: celery -A aip_project worker -l info
    env_file: .env
    depends_on:
      - postgres
      - redis
  
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379"

volumes:
  web-static:
  pgdata:
